package me.elsiff.morefish.resource

import me.elsiff.morefish.resource.configuration.FileConfigurationHandler

/**
 * Created by elsiff on 2018-12-28.
 */

class LangResource : FileConfigurationHandler() {
    val version by IntValue("version")
    val catchFish by StringValue("catch-fish")
    val get1st by StringValue("get-1st")
    val noFishingAllowed by StringValue("no-fishing-allowed")
    val contestStart by StringValue("contest-start")
    val contestStartTimer by StringValue("contest-start-timer")
    val contestStop by StringValue("contest-stop")
    val timerBossBar by StringValue("timer-boss-bar")
    val timeFormatMinutes by StringValue("time-format-minutes")
    val timeFormatSeconds by StringValue("time-format-seconds")
    val topList by StringValue("top-list")
    val topNoRecord by StringValue("top-no-record")
    val topMine by StringValue("top-mine")
    val topMineNoRecord by StringValue("top-mine-no-record")
    val reward by StringValue("reward")
    val rewardCashPrize by StringValue("reward-cash-prize")
    val noPermission by StringValue("no-permission")
    val alreadyOngoing by StringValue("already-ongoing")
    val alreadyStopped by StringValue("already-stopped")
    val notNumber by StringValue("not-number")
    val notPositive by StringValue("not-positive")
    val notOngoing by StringValue("not-ongoing")
    val clearRecords by StringValue("clear-records")
    val reloadConfig by StringValue("reload-config")
    val failedToReload by StringValue("failed-to-reload")
    val inGameCommand by StringValue("in-game-command")
    val shopDisabled by StringValue("shop-disabled")
    val playerNotFound by StringValue("player-not-found")
    val forcedPlayerToShop by StringValue("forced-player-to-shop")
    val invalidCommand by StringValue("invalid-command")
    val rewardsGuiTitle by StringValue("rewards-gui-title")
    val rewardsGuideIconName by StringValue("rewards-guide-icon-name")
    val rewardsGuideIconLore by StringListValue("rewards-guide-icon-lore")
    val rewardsSignIconName by StringValue("rewards-sign-icon-name")
    val rewardsSignIconLore by StringListValue("rewards-sign-icon-lore")
    val rewardsConsolation by StringValue("rewards-consolation")
    val rewardsEmeraldIconName by StringValue("rewards-emerald-icon-name")
    val rewardsEmeraldIconLore by StringListValue("rewards-emerald-icon-lore")
    val enterCashPrize by StringListValue("enter-cash-prize")
    val enteredCancel by StringValue("entered-cancel")
    val enteredNotNumber by StringValue("entered-not-number")
    val enteredNotPositive by StringValue("entered-not-positive")
    val enteredSuccessfully by StringValue("entered-successfully")
    val savedChanges by StringValue("saved-changes")
    val shopGuiTitle by StringValue("shop-gui-title")
    val shopEmeraldIconName by StringValue("shop-emerald-icon-name")
    val shopSold by StringValue("shop-sold")
    val shopNoFish by StringValue("shop-no-fish")
    val createdSignShop by StringValue("created-sign-shop")
    val oldFile by StringValue("old-file")
    val newVersion by StringListValue("new-version")
}